sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8

env: ORG_GRADLE_PROJECT_downloadIdeaSources=false

branches:
  only:
    - master
    - master2

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "Material Theme-*.zip"
after_deploy:
  - ./gradlew buildPlugin

jobs:
  - stage: Build
  - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
  - env: ORG_GRADLE_PROJECT_ideaVersion=173-SNAPSHOT
  - env: ORG_GRADLE_PROJECT_ideaVersion=2017.2.5

allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT