sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8

env: ORG_GRADLE_PROJECT_downloadIdeaSources=false

branches:
  only:
    - master
    - master2

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: script
  skip_cleanup: true
  file_glob: true
  file: "Material Theme-*.zip"
  script: ORG_GRADLE_PROJECT_publishChannels=eap ORG_GRADLE_PROJECT_version=1.15.2-eap$TRAVIS_BUILD_NUMBER ./gradlew buildPlugin
  on:
    branch: builds

jobs:
  - stage: Build
  - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
  - env: ORG_GRADLE_PROJECT_ideaVersion=173-SNAPSHOT
  - env: ORG_GRADLE_PROJECT_ideaVersion=2017.2.5

allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT